// List of known disposable/temporary email domains
// Users signing up with these domains will be rejected
export const DISPOSABLE_DOMAINS = new Set([
  // Popular disposable email services
  'yopmail.com', 'yopmail.fr', 'yopmail.net',
  'tempmail.com', 'temp-mail.org', 'temp-mail.io',
  'guerrillamail.com', 'guerrillamail.net', 'guerrillamail.org', 'guerrillamail.de', 'grr.la', 'guerrillamailblock.com',
  'mailinator.com', 'mailinator2.com', 'mailinator.net',
  'throwaway.email', 'throwaway.com',
  'sharklasers.com', 'guerrillamail.info', 'spam4.me',
  'trashmail.com', 'trashmail.me', 'trashmail.net', 'trashmail.org',
  'dispostable.com',
  'mailnesia.com',
  'maildrop.cc',
  'fakeinbox.com',
  'mailcatch.com',
  'tempail.com',
  'tempmailaddress.com',
  'emailondeck.com',
  'getnada.com', 'nada.email',
  'tempinbox.com',
  'mailtemp.org',
  'mohmal.com',
  'burnermail.io',
  'discard.email',
  'discardmail.com', 'discardmail.de',
  'minutemail.com',
  'tempr.email',
  'tempmailo.com',
  'emailfake.com',
  'crazymailing.com',
  'mailsac.com',
  'inboxbear.com',
  'mytemp.email',
  'tmpmail.net', 'tmpmail.org',
  'harakirimail.com',
  'getairmail.com',
  'tmail.ws',
  'mohmal.im',
  'mailnator.com',
  'tempsky.com',
  'spambox.us',
  'trashymail.com',
  'trashymail.net',
  'wegwerfmail.de', 'wegwerfmail.net', 'wegwerfmail.org',
  'mail-temporaire.fr',
  'jetable.org', 'jetable.com', 'jetable.net', 'jetable.fr.nf',
  'mytrashmail.com',
  'yep.it',
  'spamgourmet.com', 'spamgourmet.net',
  'mailexpire.com',
  'tempemails.io',
  'incognitomail.org', 'incognitomail.com',
  'anonymbox.com',
  'mailnull.com',
  'deadaddress.com',
  'mailmoat.com',
  'spamcero.com',
  'e4ward.com',
  'mailzilla.com',
  'filzmail.com',
  'spamfree24.org',
  'binkmail.com',
  'safetymail.info',
  'mailhazard.com', 'mailhazard.us',
  'mailquack.com',
  'objectmail.com',
  'proxymail.eu',
  'rcpt.at',
  'trashmail.at',
  'sogetthis.com',
  'spamavert.com',
  'uggsrock.com',
  'mailblocks.com',
  'despam.it',
  'fakemailgenerator.com',
  'armyspy.com', 'cuvox.de', 'dayrep.com', 'einrot.com', 'fleckens.hu',
  'gustr.com', 'jourrapide.com', 'rhyta.com', 'superrito.com', 'teleworm.us',
  '10minutemail.com', '10minutemail.net', '10minutemail.org',
  '20minutemail.com', '20minutemail.it',
  'mailforspam.com',
  'trash-mail.at', 'trash-mail.com',
  'mailnesia.com',
  'spamhereplease.com',
  'devnullmail.com',
  'klzlk.com',
  'meltmail.com',
  'spaml.de', 'spaml.com',
  'disposableemailaddresses.emailmiser.com',
  'mintemail.com',
  'spamspot.com',
  'emailigo.de',
  'emailsensei.com',
  'emz.net',
  'enterto.com',
  'fr33mail.info',
  'greensloth.com',
  'h8s.org',
  'haltospam.com',
  'ichimail.com',
  'imails.info',
  'instant-mail.de',
  'ipoo.org',
  'irish2me.com',
  'jetable.pp.ua',
  'jnxjn.com',
  'kasmail.com',
  'koszmail.pl',
  'kurzepost.de',
  'lifebyfood.com',
  'lookugly.com',
  'lr78.com',
  'lroid.com',
  'maileater.com',
  'mailexpire.com',
  'mailforspam.com',
  'mailfreeonline.com',
  'mailin8r.com',
  'mailincubator.com',
  'mailme.ir',
  'mailme.lv',
  'mailmetrash.com',
  'mailshell.com',
  'mailsiphon.com',
  'mailslite.com',
  'mailtemporaire.com', 'mailtemporaire.fr',
  'mailzilla.org',
  'mbx.cc',
  'mega.zik.dj',
  'meinspamschutz.de',
  'moncourrier.fr.nf',
  'monemail.fr.nf',
  'monmail.fr.nf',
  'nomail.xl.cx',
  'nospam.ze.tc',
  'nurfuerspam.de',
  'nus.edu.sg',
  'oneoffemail.com',
  'online.ms',
  'oopi.org',
  'ordinaryamerican.net',
  'owlpic.com',
  'pjjkp.com',
  'plexolan.de',
  'pookmail.com',
  'privacy.net',
  'proxymail.eu',
  'put2.net',
  'qq.com',
  'quickinbox.com',
  'rcpt.at',
  'recode.me',
  'regbypass.com',
  'rhyta.com',
  's0ny.net',
  'safe-mail.net',
  'safersignup.de',
  'safetypost.de',
  'sandelf.de',
  'saynotospams.com',
  'scatmail.com',
  'schafmail.de',
  'selfdestructingmail.com',
  'shieldedmail.com',
  'shortmail.net',
  'skeefmail.com',
  'slaskpost.se',
  'slipry.net',
  'slopsbox.com',
  'smashmail.de',
  'soodonims.com',
  'spam.la', 'spam.su',
  'spamavert.com',
  'spambob.com', 'spambob.net', 'spambob.org',
  'spambox.info', 'spambox.irishspringrealty.com', 'spambox.us',
  'spamcannon.com', 'spamcannon.net',
  'spamcero.com',
  'spamcon.org',
  'spamcorptastic.com',
  'spamcowboy.com', 'spamcowboy.net', 'spamcowboy.org',
  'spamday.com',
  'spamex.com',
  'spamfighter.cf', 'spamfighter.ga', 'spamfighter.gq', 'spamfighter.ml', 'spamfighter.tk',
  'spamfree.eu', 'spamfree24.com', 'spamfree24.de', 'spamfree24.eu', 'spamfree24.info', 'spamfree24.net',
  'spamhole.com',
  'spamify.com',
  'spaminator.de',
  'spamkill.info',
  'spaml.com', 'spaml.de',
  'spammotel.com',
  'spamobox.com',
  'spamoff.de',
  'spamslicer.com',
  'spamstack.net',
  'spamtrail.com',
  'spamtrap.ro',
  'speed.1s.fr',
  'suremail.info',
  'teewars.org',
  'tempalias.com',
  'tempe4mail.com',
  'tempemail.co.za', 'tempemail.com', 'tempemail.net',
  'tempinbox.co.uk', 'tempinbox.com',
  'tempmail2.com', 'tempmail.it',
  'tempmailer.com', 'tempmailer.de',
  'tempomail.fr',
  'temporarioemail.com.br',
  'temporaryemail.net', 'temporaryemail.us',
  'temporaryforwarding.com',
  'temporaryinbox.com',
  'temporarymailaddress.com',
  'thankyou2010.com',
  'thisisnotmyrealemail.com',
  'throwawayemailaddress.com',
  'tittbit.in',
  'tradermail.info',
  'trash2009.com', 'trash2010.com', 'trash2011.com',
  'trashdevil.com', 'trashdevil.de',
  'trashemail.de',
  'trashmail.de', 'trashmail.io', 'trashmail.ws',
  'trashmailer.com',
  'trashymail.com', 'trashymail.net',
  'turual.com',
  'twinmail.de',
  'tyldd.com',
  'uggsrock.com',
  'upliftnow.com',
  'uplipht.com',
  'venompen.com',
  'veryreallyfakeemails.com',
  'vidchart.com',
  'viditag.com',
  'viewcastmedia.com', 'viewcastmedia.net', 'viewcastmedia.org',
  'vomoto.com',
  'vpn.st',
  'vsimcard.com',
  'vubby.com',
  'wasteland.rfc822.org',
  'webemail.me',
  'weg-werf-email.de',
  'wegwerfadresse.de',
  'wegwerfemail.com', 'wegwerfemail.de',
  'wegwerfmail.de', 'wegwerfmail.info', 'wegwerfmail.net', 'wegwerfmail.org',
  'wh4f.org',
  'whatiaas.com',
  'whatpaas.com',
  'whyspam.me',
  'wikidocuslice.com',
  'willselfdestruct.com',
  'winemaven.info',
  'wronghead.com',
  'wuzup.net', 'wuzupmail.net',
  'wwwnew.eu',
  'xagloo.com',
  'xemaps.com',
  'xents.com',
  'xjoi.com',
  'xmaily.com',
  'xoxy.net',
  'yapped.net',
  'yep.it',
  'yogamaven.com',
  'yuurok.com',
  'zehnminutenmail.de',
  'zippymail.info',
  'zoaxe.com',
  'zoemail.org',
])

export function isDisposableEmail(email: string): boolean {
  const domain = email.split('@')[1]?.toLowerCase()
  if (!domain) return true
  return DISPOSABLE_DOMAINS.has(domain)
}
